name: Run Tests

on: [push, pull_request]

jobs:
  unittest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python }}
      - name: Install pytest and parameterized
        run: pip install pytest parameterized
      - name: Run test
        run: python -m unittest test_cfn.py
